In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split

In [2]:
basic_colors = pd.read_csv('BasicColors.csv')
basic_colors

Name    R    G    B          RGB
0    Black    0    0    0        0,0,0
1    White  255  255  255  255,255,255
2      Red  255    0    0      255,0,0
3   Orange  255  165    0    255,165,0
4     Blue    0    0  255      0,0,255
5   Yellow  255  255    0    255,255,0
6     Grey  128  128  128  128,128,128
7    Green    0  128    0      0,128,0
8   Purple  128    0  128    128,0,128
9    Brown  165   42   42    165,42,42
10    Pink  255  192  203  255,192,203

In [3]:
df = pd.read_csv('final_data.csv')
df.head()

red  green  blue  label
0   20    139   240   Blue
1  174     83    72  Brown
2  144    249   131  Green
3  168     25   156   Pink
4   30    182   136  Green

Preprocessing

In [4]:
le = LabelEncoder()

In [5]:
label_encoded = le.fit_transform(df['label'])

In [6]:
label_encoded

array([1, 2, 3, ..., 0, 0, 0])

In [7]:
df['label_encoded'] = label_encoded

In [8]:
df

red  green  blue  label  label_encoded
0      20    139   240   Blue              1
1     174     83    72  Brown              2
2     144    249   131  Green              3
3     168     25   156   Pink              6
4      30    182   136  Green              3
...   ...    ...   ...    ...            ...
5047   26     26    26  Black              0
5048   27     27    27  Black              0
5049   28     28    28  Black              0
5050   29     29    29  Black              0
5051   30     30    30  Black              0

[5052 rows x 5 columns]

In [65]:
df[['label', 'label_encoded']].value_counts()

label   label_encoded
Green   3                1457
Blue    1                1107
Pink    6                 579
Purple  7                 553
Brown   2                 376
Yellow  10                285
Red     8                 236
Orange  5                 205
Grey    4                 174
Black   0                  51
White   9                  29
dtype: int64

In [10]:
X = np.array([])
for index, color in enumerate(df['label']):
    colors = []
    colors.append(df['red'][index])
    colors.append(df['blue'][index])
    colors.append(df['green'][index])

    X = np.append(X, colors, axis=0)

In [11]:
X

array([ 20., 240., 139., ...,  30.,  30.,  30.])

In [12]:
X = X.astype('int64')

In [13]:
X.shape

(15156,)

In [14]:
X

array([ 20, 240, 139, ...,  30,  30,  30], dtype=int64)

In [15]:
X = X.reshape(5052, 3)

In [16]:
y = np.array(label_encoded)

In [17]:
X.shape

(5052, 3)

In [18]:
y.shape

(5052,)

In [19]:
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.2, random_state=1)

Building Model

In [172]:
model = KNeighborsClassifier(n_neighbors = 3)
model

KNeighborsClassifier(n_neighbors=3)

Train Model

In [174]:
# model.fit(train_X, train_y)
model.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

Test Model

In [147]:
model.predict(val_X)

array([ 3,  1,  6, ..., 10,  7,  6])

In [149]:
val_y

array([10,  1,  7, ..., 10,  7,  6])

In [151]:
model.predict([[2, 33, 170]])

array([3])

Works but isnt as impressive, need to build an image graber 

In [23]:
from image_reader import ImageReader

In [24]:
im = ImageReader()

In [25]:
# im.clear_directory()
# im.create_colors()

In [100]:
df[['label', 'label_encoded']].value_counts()

label   label_encoded
Green   3                1457
Blue    1                1107
Pink    6                 579
Purple  7                 553
Brown   2                 376
Yellow  10                285
Red     8                 236
Orange  5                 205
Grey    4                 174
Black   0                  51
White   9                  29
dtype: int64

In [155]:
def return_colorname(label):
    color_to_label = df[['label', 'label_encoded']].value_counts().index
    for index, name in enumerate(color_to_label):
        if(color_to_label[index][1] == label):
            return str(color_to_label[index][0])

In [142]:
return_colorname(7)

'Purple'

In [153]:
colors = im.read_directory()
colors

[(52, 97, 6),
 (60, 108, 171),
 (30, 199, 105),
 (245, 204, 104),
 (52, 118, 129),
 (93, 109, 237),
 (4, 10, 210),
 (214, 162, 149),
 (116, 206, 16),
 (249, 83, 12)]

The Predicted Results

In [138]:
color_values = np.array([])
for index, color in enumerate(colors):
    color_values = np.append(color_values, model.predict([color]))
    color_values = np.array(color_names).flatten()

In [141]:
for value in color_values:
    print(return_colorname(value))

Purple
Green
Blue
Pink
Green
Green
Green
Pink
Purple
Red


The actual colors

In [161]:
for color in colors:
    col_val = model.predict([color])
    print(return_colorname(col_val))

Purple
Green
Blue
Pink
Green
Green
Green
Pink
Purple
Red


In [180]:
return_colorname(model.predict([[255, 139, 240]]))

'Yellow'